/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// RCC register
#define RCC_APB2ENR  (*((volatile uint32_t *)0x40021018))

// GPIOA registers
#define GPIOA_CRH    (*((volatile uint32_t *)0x40010804))

// UART1 registers
#define USART1_SR    (*((volatile uint32_t *)0x40013800))
#define USART1_DR    (*((volatile uint32_t *)0x40013804))
#define USART1_BRR   (*((volatile uint32_t *)0x40013808))
#define USART1_CR1   (*((volatile uint32_t *)0x4001380C))

void delay(volatile uint32_t count) {
    while(count--);
}

void uart_send_char(char c) {
    // wait until transmit buffer is empty
    while(!(USART1_SR & (1 << 7)));
    USART1_DR = c;
}

void uart_send_string(char *str) {
    while(*str) {
        uart_send_char(*str);
        str++;
    }
}

int main(void) {

    // Step 1 — Enable clocks for GPIOA and UART1
    RCC_APB2ENR |= (1 << 2);  // GPIOA clock
    RCC_APB2ENR |= (1 << 14); // UART1 clock

    // Step 2 — Configure PA9 as UART TX (alternate function push-pull)
    GPIOA_CRH &= ~(0xF << 4);
    GPIOA_CRH |=  (0xB << 4);

    // Step 3 — Configure UART1
    // Baud rate 9600 at 8MHz system clock
    // BRR = 8000000 / 9600 = 833 = 0x341
    USART1_BRR = 0x341;

    // Enable UART transmitter and UART itself
    USART1_CR1 |= (1 << 3);  // TE - transmitter enable
    USART1_CR1 |= (1 << 13); // UE - UART enable

    // Step 4 — Send hello forever
    while(1) {
        uart_send_string("Hello from STM32!\r\n");
        delay(1000000);
    }
}
